//
//  WeatherUpKit.swift
//  WeatherUp
//
//  Created by charmaex on 02.04.16.
//  Copyright (c) 2016 charmaex. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class WeatherUpKit : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(frame frame: CGRect = CGRectMake(0, 0, 100, 100), arrowColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000), arrowValue: CGFloat = 0) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let arrowCalc: CGFloat = arrowValue * 90
        let upper: CGFloat = arrowCalc + 45
        let lower: CGFloat = -arrowCalc - 45


        //// Subframes
        let group: CGRect = CGRectMake(frame.minX + 5, frame.minY + 5, frame.width - 10, frame.height - 10)


        //// Group
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Mask
        let maskPath = UIBezierPath(ovalInRect: CGRectMake(group.minX + floor(group.width * 0.00000 + 0.5), group.minY + floor(group.height * 0.00000 + 0.5), floor(group.width * 1.00000 + 0.5) - floor(group.width * 0.00000 + 0.5), floor(group.height * 1.00000 + 0.5) - floor(group.height * 0.00000 + 0.5)))
        maskPath.addClip()


        //// Arrow Drawing
        let arrowRect = CGRectMake(group.minX + floor(group.width * -0.03333 + 0.5), group.minY + floor(group.height * -0.03333 + 0.5), floor(group.width * 1.03333 + 0.5) - floor(group.width * -0.03333 + 0.5), floor(group.height * 1.03333 + 0.5) - floor(group.height * -0.03333 + 0.5))
        let arrowPath = UIBezierPath()
        arrowPath.addArcWithCenter(CGPointMake(arrowRect.midX, arrowRect.midY), radius: arrowRect.width / 2, startAngle: -lower * CGFloat(M_PI)/180, endAngle: -upper * CGFloat(M_PI)/180, clockwise: true)
        arrowPath.addLineToPoint(CGPointMake(arrowRect.midX, arrowRect.midY))
        arrowPath.closePath()

        arrowColor.setStroke()
        arrowPath.lineWidth = 2
        arrowPath.stroke()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

}
