//
//  WeatherUpKit.swift
//  WeatherUp
//
//  Created by charmaex on 19.08.17.
//  Copyright © 2017 charmaex. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

import UIKit

public class WeatherUpKit: NSObject {

	/// / Drawing Methods

	@objc public dynamic class func drawCanvas1(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100), arrowColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000), arrowValue: CGFloat = 0) {
		/// / General Declarations
		let context = UIGraphicsGetCurrentContext()!

		// This non-generic function dramatically improves compilation times of complex expressions.
		func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

		/// / Variable Declarations
		let arrowCalc: CGFloat = arrowValue * 90
		let upper: CGFloat = arrowCalc + 45
		let lower: CGFloat = -arrowCalc - 45

		/// / Subframes
		let group: CGRect = CGRect(x: frame.minX + 5, y: frame.minY + 5, width: frame.width - 10, height: frame.height - 10)

		/// / Group
		context.saveGState()
		context.beginTransparencyLayer(auxiliaryInfo: nil)

		/// / Clip Mask
		let maskPath = UIBezierPath(ovalIn: CGRect(x: group.minX + fastFloor(group.width * 0.00000 + 0.5), y: group.minY + fastFloor(group.height * 0.00000 + 0.5), width: fastFloor(group.width * 1.00000 + 0.5) - fastFloor(group.width * 0.00000 + 0.5), height: fastFloor(group.height * 1.00000 + 0.5) - fastFloor(group.height * 0.00000 + 0.5)))
		maskPath.addClip()

		/// / Arrow Drawing
		let arrowRect = CGRect(x: group.minX + fastFloor(group.width * -0.03333 + 0.5), y: group.minY + fastFloor(group.height * -0.03333 + 0.5), width: fastFloor(group.width * 1.03333 + 0.5) - fastFloor(group.width * -0.03333 + 0.5), height: fastFloor(group.height * 1.03333 + 0.5) - fastFloor(group.height * -0.03333 + 0.5))
		let arrowPath = UIBezierPath()
		arrowPath.addArc(withCenter: CGPoint(x: arrowRect.midX, y: arrowRect.midY), radius: arrowRect.width / 2, startAngle: -lower * CGFloat.pi / 180, endAngle: -upper * CGFloat.pi / 180, clockwise: true)
		arrowPath.addLine(to: CGPoint(x: arrowRect.midX, y: arrowRect.midY))
		arrowPath.close()

		arrowColor.setStroke()
		arrowPath.lineWidth = 2
		arrowPath.stroke()

		context.endTransparencyLayer()
		context.restoreGState()
	}
}
